### ISSUE TITLE
Button.json not found problem

### ISSUE THREAD

**Issue by doanbactam** [MurkyYT/CSAuto#23]
Button.json not found problem

10/10/2023 16:03:35 CRITICAL - Could not find a part of the path 'C:\Users\1\AppData\Local\Murky\CSAuto.exe_Url_zhdjx3b4psaxfc22a3bqzmz22xjq32ax\1.0.0.0\buttons.json'.
StackTrace:   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at CSAuto.DiscordRPCButtonSerializer.Serialize(List`1 buttons)
   at CSAuto.App.OnStartup(StartupEventArgs e)
   at System.Windows.Application.<.ctor>b__1_0(Object unused)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
Source: mscorlib
Inner Exception:

**Comment by MurkyYT** [comment]
I will fix it as soon as possible, thanks for reporting

**Comment by MurkyYT** [comment]
@doanbactam 
The new version should fix your issue.
If you have any issue comment here!
